#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#

PROJECT_NAME := motor_control

EXTRA_COMPONENT_DIRS := $(IDF_PATH)/examples/common_components/protocol_examples_common $(CURDIR)/components


include $(IDF_PATH)/make/project.mk

